// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2i00uAp0UjJKyQ6r-aoql4SQvqW8PJc',
    appId: '1:733285628701:web:886a33c1262648ec50fff4',
    messagingSenderId: '733285628701',
    projectId: 'todo-list-app-bc985',
    authDomain: 'todo-list-app-bc985.firebaseapp.com',
    storageBucket: 'todo-list-app-bc985.appspot.com',
    measurementId: 'G-PLQ28578CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACaqojRqrQd3pk8AsDzNDgYlZMnD5OJsg',
    appId: '1:733285628701:android:9db848f70ad57d3150fff4',
    messagingSenderId: '733285628701',
    projectId: 'todo-list-app-bc985',
    storageBucket: 'todo-list-app-bc985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYZn7Zzi39kKqD_8fAn5bWvmRK-Dtnjk',
    appId: '1:733285628701:ios:10278c0d7ea33e5750fff4',
    messagingSenderId: '733285628701',
    projectId: 'todo-list-app-bc985',
    storageBucket: 'todo-list-app-bc985.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwYZn7Zzi39kKqD_8fAn5bWvmRK-Dtnjk',
    appId: '1:733285628701:ios:5ce4d11dbd4e288550fff4',
    messagingSenderId: '733285628701',
    projectId: 'todo-list-app-bc985',
    storageBucket: 'todo-list-app-bc985.appspot.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
